### ISSUE TITLE
[资源贡献] 矩阵理论PPT以及教材pdf

### ISSUE THREAD

**Issue by jaysonder** [Xovee/uestc-course#101]
点击紧贴本输入框下方的文字，即可选择文件进行上传，或者直接拖拽文件至本输入框。如果有多个文件，建议先压缩为 ZIP 文件。
再次感谢。
[PPT以及教材.zip](https://github.com/user-attachments/files/16676170/PPT.zip)

**Comment by Xovee** [comment]
感谢贡献资源，PPT及教材可能设计版权问题，暂不收录。这些资源大部分学生应不难以获取。
