### ISSUE TITLE
[问题报告] 矩阵理论下载时提示输入路径错误请重新输入

### ISSUE THREAD

**Issue by OxideCalcium** [Xovee/uestc-course#103]
如题，点击矩阵理论链接提示路径错误请重新输入，单独输入子文件路径也无法成功。

**Comment by Xovee** [comment]
我测试了一下，下载功能应该是没问题的。矩阵理论内资源多、文件较大，可能网速或者墙会影响下载效率，我一时半会也没下载成功。你试一试下载一下其他的文件夹资源呢？比如C语言，应该几秒就下载成功了。如果实在不行，可以手动下载每一个文件或者clone 项目。

**Comment by Xovee** [comment]
也有可能是Github Token API达到limits了。
