### ISSUE TITLE
[问题报告] 复习资料README文件命名错误

### ISSUE THREAD

**Issue by Xovee** [Xovee/uestc-course#27]
**问题描述**
页面位置：
https://github.com/Xovee/uestc-course/tree/master/%E8%AF%BE%E7%A8%8B%E7%9B%AE%E5%BD%95/Unix%26Linux%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E5%86%85%E6%A0%B8%E7%BB%93%E6%9E%84/%E5%A4%8D%E4%B9%A0%E8%B5%84%E6%96%99

**解决方案**
修改README文件名

**Comment by MortonWang** [comment]
已经修改完毕 thx
👍
