### ISSUE TITLE
[问题报告] 随机试卷 转制格式问题

### ISSUE THREAD

**Issue by MortonWang** [Xovee/uestc-course#29]
**随机试卷bug**

第3题中的  1/4 太小了

页面地址：https://github.com/Xovee/uestc-course/blob/6adb2cb219792b19b7ced2aa50bade29b079e9d1/%E8%AF%BE%E7%A8%8B%E7%9B%AE%E5%BD%95/%E9%9A%8F%E6%9C%BA%E8%BF%87%E7%A8%8B%E4%B8%8E%E6%8E%92%E9%98%9F%E8%AE%BA/%E5%8E%86%E5%B9%B4%E8%AF%95%E9%A2%98/2014%E5%B9%B4%E6%98%A5-%E6%9C%9F%E6%9C%AB%E8%80%83%E8%AF%95-%E6%97%A0%E7%AD%94%E6%A1%88.pdf

**Comment by MortonWang** [comment]
**随机试卷bug**

- 填空题 2 中“索赔时车险”-->"索赔是车险"
- 第6题 “发送故障”——>"发生故障"，共2处

页面地址：https://github.com/Xovee/uestc-course/blob/322eeb82ab467a4e9e17d2d2bdf0d216d907562a/%E8%AF%BE%E7%A8%8B%E7%9B%AE%E5%BD%95/%E9%9A%8F%E6%9C%BA%E8%BF%87%E7%A8%8B%E4%B8%8E%E6%8E%92%E9%98%9F%E8%AE%BA/%E5%8E%86%E5%B9%B4%E8%AF%95%E9%A2%98/2017%E5%B9%B4-%E6%9C%9F%E6%9C%AB%E8%80%83%E8%AF%95-%E9%83%A8%E5%88%86%E7%AD%94%E6%A1%88.pdf

**Comment by MortonWang** [comment]
这里还有个小 bug，请修改后一并提交。

页面地址：https://github.com/Xovee/uestc-course/pull/28

**Comment by MortonWang** [comment]
**分支合并 bug**

将 #28 合并后 发现被关闭的 #24 没有合并到 master 中

**Comment by Xovee** [comment]
bug已修正，失误操作直接提到master了，就这样吧。
我把 #24 的改动转移到 #28 了，所以不要管 #24 了。
