### ISSUE TITLE
请问一下试卷题目: 考试科目·排队论这个在latex里怎么实现

### ISSUE THREAD

**Issue by ifeelok92** [Xovee/uestc-course#43]
试卷开始写题目, 考试形式, 时间这些latex应该怎么写, 在mit那个参考资料没找到解决方案. 此外, 如果试卷开头还需要写 姓名:______________  学号:________________  这些, 又该如何用latex实现?

**Comment by Xovee** [comment]
> 试卷开始写题目, 考试形式, 时间这些latex应该怎么写, 在mit那个参考资料没找到解决方案. 此外, 如果试卷开头还需要写 姓名:______________ 学号:________________ 这些, 又该如何用latex实现?

可以参考一下我的这篇文章《[使用 LaTeX 制作考试试卷](https://blog.csdn.net/xovee/article/details/90599346)》。

**Comment by Xovee** [comment]
`姓名：\fillin[2cm] 学号：\fillin[2cm]`

**Comment by ifeelok92** [comment]
我参考了你的"使用LaTex制作考试试卷", 但是试卷开头那个 **考试科目**, **考试时间**那块的内容, 在文章里没有讲.

**Comment by Xovee** [comment]
> 我参考了你的"使用LaTex制作考试试卷", 但是试卷开头那个 **考试科目**, **考试时间**那块的内容, 在文章里没有讲.

这个在`\begin{document}`之后使用正常的文档流即可实现，你可以使用任何`LaTeX`语法去实现这一部分。

样板里的代码如下：
```python
{\noindent \Large \bf{考试科目：\underline{矩阵理论}\\考试形式：\underline{闭卷}\\考试日期：\underline{2017年秋}\\考试时长：\underline{2小时}}}
```
其中`\\`代表换行，不需要换行的可以去掉，空下划线可以使用`\fillin[]`，方括号内填写下划线的长度即可，例如`2cm`。
