### ISSUE TITLE
[功能建议] 开源课程实验 & 代码的索引

### ISSUE THREAD

**Issue by LolipopJ** [Xovee/uestc-course#53]
**功能建议**

在 Github 上有很多电子科技大学同学们开源的**课程实验或代码**仓库，例如：

- [uestc_Internet_plus_course_project](https://github.com/543877815/uestc_Internet_plus_course_project)
- [Matu-UESTC-Programming-Starting](https://github.com/Luosuu/Matu-UESTC-Programming-Starting)
- [UESTC-Programming-Course](https://github.com/HeRaNO/UESTC-Programming-Course)
- [MachineLearing-Homework](https://github.com/Eternity-Myth/MachineLearing-Homework)
- [2019_UESTC_C_Project](https://github.com/Jason-xy/2019_UESTC_C_Project)
- 以及我的 [coursework-repo](https://github.com/LolipopJ/coursework-repo) 等等

相较于上网检索相关资料，这些开源仓库存储的课程实验及代码可能更具有代表性和实用性。

既满足仓库所推崇的**推动知识传播、提高资源质量并减少获取成本**目标；同时也可以鼓励更多的同学，或者说告诉大家还可以开源并共享自己的课程实验及代码等相关内容。

因此，建议在 `README.md` 中新增条目例如：

---

## 课程实验及代码索引

仓库名|仓库作者|仓库简介
---|---|---
[uestc_Internet_plus_course_project](https://github.com/543877815/uestc_Internet_plus_course_project)|[543877815](https://github.com/543877815)|作者在电子科大本科期间所有课程课设和作业的代码和部分报告，包括【计算机组成与结构】、【计算机网络与通信技术】、【软件基础综合课程设计】、【互联网软件开发综合课程设计】等
[coursework-repo](https://github.com/LolipopJ/coursework-repo)|[LolipopJ](https://github.com/LolipopJ)|2018 - 2022 年，就读于电子科技大学（UESTC）软件工程（互联网“＋”）专业，本科期间所写的课程作业代码及完成的实验报告

---

**Comment by Xovee** [comment]
@LolipopJ 感谢您提供的建议。

此类资源所存储的课程实验及代码很有参考价值，不过直接链接于仓库主页，并不直观。

我的建议是：
- 放置超链接类的办法：
  对于某个repo，如果里面有多种课程的实验和代码，应当在本仓库的对应课程主页增加【实验&代码】章节，然后将仓库名称和地址链接在对应表格里，链接应直接对应repo中某个实验的具体文件夹，而非repo首页
- 直接将对应repo的资源整合到本仓库中
  在课程文件夹中增加新的文件夹，或将新增资源放置在【复习资料】文件夹中，然后在主页描述新增资源的介绍

这样更有利于资源寻找者定位自己所需要的资源。

**Comment by LolipopJ** [comment]
@Xovee **放置超链接类的方法**很好！

直接整合 repo 中的资源可能工程量会比较大，而且系一种重复劳动。

目前课程资料包含四个类型：【复习资料】、【历年试题】、【作业】和【教材】，通常都会存放文件，所以单独开文件夹很不错。

但如果用超链接的方式，单独开文件夹【实验&代码】可能略显臃肿，也许可以考虑放在**课程主页**或者放在**课程的【作业】章节**中。

**Comment by Xovee** [comment]
> @Xovee **放置超链接类的方法**很好！
> 
> 直接整合 repo 中的资源可能工程量会比较大，而且系一种重复劳动。
> 
> 目前课程资料包含四个类型：【复习资料】、【历年试题】、【作业】和【教材】，通常都会存放文件，所以单独开文件夹很不错。
> 
> 但如果用超链接的方式，单独开文件夹【实验&代码】可能略显臃肿，也许可以考虑放在**课程主页**或者放在**课程的【作业】章节**中。

@LolipopJ 超链接的话放在课程主页比较好，直接整合资源的话在【作业】里新开文件夹比较好，其实工程量并不会特别大。

主要的担忧应该是后续实验代码更新的问题，不过课程结束之后这些代码一般也应该处于archive的状态，问题应该不会很大。
