### ISSUE TITLE
[资源贡献] 计算机组成原理练习题与答案

### ISSUE THREAD

**Issue by hzy-hzy** [Xovee/uestc-course#59]
[计组练习题及答案.zip](https://github.com/Xovee/uestc-course/files/5861706/default.zip)

点击紧贴本输入框下方的文字，即可选择文件进行上传，或者直接拖拽文件至本输入框。如果有多个文件，建议先压缩为 ZIP 文件。
再次感谢。

**Comment by Xovee** [comment]
感谢资源贡献！已添加～
