### ISSUE TITLE
[资源贡献] 计算机图形学

### ISSUE THREAD

**Issue by muzili028** [Xovee/uestc-course#67]
点击紧贴本输入框下方的文字，即可选择文件进行上传，或者直接拖拽文件至本输入框。如果有多个文件，建议先压缩为 ZIP 文件。
再次感谢。
[计算机图形学-复习资料.zip](https://github.com/Xovee/uestc-course/files/6662860/-.zip)

**Comment by Xovee** [comment]
感谢资源贡献！已合并到主仓库。

您可以在*贡献者名单*中添加自己的名字~
