### ISSUE TITLE
[资源贡献] 

### ISSUE THREAD

**Issue by QianMo-wangxiaoyu** [Xovee/uestc-course#73]
因为是之前在百度网盘整理过了，下载比较麻烦，所以直接放了一个分享码，希望谅解，课程是计算机学院本科网络空间安全的部分课程的ppt
链接：https://pan.baidu.com/s/1UplEn0RESWso-hQGnCrLTA 
提取码：e36j

**Comment by Xovee** [comment]
非常感谢。整理检查之后我将合并到主仓库。

**Comment by Xovee** [comment]
@QianMo-wangxiaoyu 你好，资源已经检查并合并到主仓库了。

其中，因为课件涉及到版权问题，以及大多数同学其实是有课件的（属于不难获取的资源），故没有收录。

你可以在[贡献者名单](https://github.com/Xovee/uestc-course/blob/master/assets/贡献者名单.md)中添加自己的名字和留言。

再次感谢:heart:
