### ISSUE TITLE
好像下载不了了

### ISSUE THREAD

**Issue by icyriverwolf** [Xovee/uestc-course#78]
**如果您的建议是由于仓库的缺陷**
请在这里清晰、简明地描述仓库的缺陷。

**功能建议**
请在这里清晰、简明地描述您对仓库的功能建议。

**替代方案**
如果您有考虑过任何替代方案的话，请在这里描述。

**其他问题**
请在这里描述其他问题，例如截图等

**Comment by Xovee** [comment]
我刚试了一下，可以下载。

对于文件很多很大的课程，需要等待的时间会比较长，建议耐心等待。

如果还不行，可以尝试清空缓存，换浏览器等。

如果还还不行，建议一个一个文件手动下载。
