### ISSUE TITLE
UESTC 拼写错误

### ISSUE THREAD

**Issue by Yaossg** [Xovee/uestc-course#79]
你的 Github 主页的 Overview 里面的 UESTC 拼错了
![image](https://user-images.githubusercontent.com/29620619/170801471-481530df-ba9a-43db-a186-78abee9e64b7.png)

原谅我找不到更好的地方反馈这个问题 :joy:

**Comment by Xovee** [comment]
哈哈哈哈非常感谢！其实点击你发的这个图的左上角的Xovee，应该就可以进入对应的仓库。
