### ISSUE TITLE
[资源贡献] 思修+英语+大物

### ISSUE THREAD

**Issue by jjq419875574** [Xovee/uestc-course#88]
点击紧贴本输入框下方的文字，即可选择文件进行上传，或者直接拖拽文件至本输入框。如果有多个文件，建议先压缩为 ZIP 文件。
再次感谢。

内有多个文件
1. 大学物理题库
2. 英语（第二学期）考试题型和新题型样题
3. 思想道德与法律基础 练习题（匹配教程2021版）
[资源（思修+英语+大物）.zip](https://github.com/Xovee/uestc-course/files/8950102/%2B.%2B.zip)

**Comment by Xovee** [comment]
非常感谢资源贡献:heart:。 

大物与思想道德资源已经合并到主仓库~你可以在贡献者名单中添加自己的留言。

再次感谢！
