### ISSUE TITLE
[资源贡献] 机电学院-电力拖动自动控制系统

### ISSUE THREAD

**Issue by zzjk1** [Xovee/uestc-course#99]
[电力拖动.docx](https://github.com/user-attachments/files/15512865/default.docx)
此为考试开卷一页纸的个人准备

**Comment by Xovee** [comment]
感谢资源贡献。请问课程名是否为【电力拖动自动控制系统】

**Comment by zzjk1** [comment]
是的



周宗杰
***@***.***







                       
原始邮件
                       
                     

发件人："Xovee Xu"< ***@***.*** &gt;;

发件时间：2024/5/31 20:27

收件人："Xovee/uestc-course"< ***@***.*** &gt;;

抄送人："zzjk1"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Xovee/uestc-course] [资源贡献] 机电学院-电力拖动自动控制系统 (Issue #99)




 
感谢资源贡献。请问课程名是否为【电力拖动自动控制系统】

**Comment by Xovee** [comment]
资源已上传到主仓库！再次感谢～
